import os
import sys
import argparse
import numpy as np
from PIL import Image
import signal
import time
signal.signal(signal.SIGINT, signal.SIG_DFL)

import OpenGL.GL as gl
from glfwBackend import glfwApp
import imgui
from imgui.integrations.glfw import GlfwRenderer

# Local imports
from fieldAnimation import FieldAnimation


#------------------------------------------------------------------------------
def E(q, r0, x, y):
    """ Return the electric field vector E=(Ex, Ey) due to charge q at r0.
    """
    den = np.hypot(x - r0[0], y - r0[1]) ** 1.5
    return q * (x - r0[0]) / den, q * (y - r0[1]) / den

#------------------------------------------------------------------------------
def createField(m=64, n=64, eq=E, charges=1):
    """ Return n x m x 2 2D array with Electric field values
        generated by a (2 * charges) electric charges configuration
        Electric field follows equation eq.
    """
    x = np.linspace(-2, 2, n)
    y = np.linspace(-2, 2, m)
    X, Y = np.meshgrid(x, y)

    # Create a multipole with nq charges of alternating sign, equally spaced
    # on the unit circle.
    nq = 2 ** int(charges)
    charges = []
    for i in range(nq):
        q = i % 2 * 2 - 1
        charges.append((q,
                (np.cos(2 * np.pi * i / nq), np.sin(2 * np.pi * i / nq))))

    Ex, Ey = np.zeros((m, n)), np.zeros((m, n))
    for charge in charges:
        ex, ey = eq(*charge, x=X, y=Y)
        Ex += ex
        Ey += ey
    return np.dstack((Ex, Ey))


#------------------------------------------------------------------------------
def userInterface(renderer, graphicItem):
    """ Control graphicItem parameters interactively
    """
    if not renderer:
        return

    renderer.process_inputs()
    imgui.new_frame()
    imgui.begin('Controls', closable=True,
            flags=imgui.WINDOW_ALWAYS_AUTO_RESIZE)

    # Speed Rate
    changed, speed = imgui.slider_float('Speed',
        graphicItem.speedFactor, 0, 10.0)
    if changed:
        graphicItem.speedFactor = speed

    # Drop Rate
    changed, dropRate = imgui.slider_float('Drop rate',
        graphicItem.dropRate, 0, 0.1)
    if changed:
        graphicItem.dropRate = dropRate

    # Drop Rate Bump
    changed, dropRateBump = imgui.slider_float('Drop rate bump',
        graphicItem.dropRateBump, 0, 0.1)
    if changed:
        graphicItem.dropRateBump = dropRateBump

    # Field Scaling
    changed, fieldScaling = imgui.slider_float('Field Scaling',
        graphicItem.fieldScaling, 0, 0.01, '%.4f')
    if changed:
        graphicItem.fieldScaling = fieldScaling

    # Unbknown const
    changed, opacity = imgui.slider_float('Opacity',
        graphicItem.fadeOpacity, 0.900, 0.999, '%.4f')
    if changed:
        graphicItem.fadeOpacity = opacity

    # Palette
    changed, color = imgui.color_edit3('Color', *graphicItem.color)
    if changed:
        graphicItem.color = color
    imgui.same_line()
    changed, palette = imgui.checkbox("Palette", graphicItem.palette)
    if changed:
        graphicItem.palette = palette

    # Point size
    changed, pointSize = imgui.input_int("Point size",
        graphicItem.pointSize, 1, 1, 1)
    if changed:
        if pointSize > 5:
            pointSize = 5
        elif pointSize < 1:
            pointSize = 1
        graphicItem.pointSize = pointSize

    # Number of Points
    changed, tracersCount = imgui.drag_int("Number of "
        "Tracers", graphicItem.tracersCount, 4096.0, 64, 1000000)
    if changed:
        graphicItem.tracersCount = tracersCount

    # Periodic border
    changed, periodic = imgui.checkbox("Periodic", graphicItem.periodic)
    if changed:
        graphicItem.periodic = periodic

    # Draw field
    changed, drawfield = imgui.checkbox("Draw Field", graphicItem.drawField)
    if changed:
        graphicItem.drawField = drawfield

    imgui.end()
    imgui.render()

#==============================================================================
class GLApp(glfwApp):
    def __init__(self, title, width, height, field, options):
        super(GLApp, self).__init__(title, width, height)

        if options.gui:
            self._renderer = GlfwRenderer(self.window(), False)
        else:
            self._renderer = None

        # Add Field Animation overlay
        self._fa = FieldAnimation(width, height, field)
        if options.draw_field:
            self._fa.drawField = True
        self._t0 = time.time()
        self._fps = 0
        self.options = options

    def renderScene(self):
        super(GLApp, self).renderScene()
        self._fa.draw()
        self._fps += 1
        userInterface(self._renderer, self._fa)
        now = time.time()
        if now - self._t0 >= 1:
            if self.options.fps:
                print("FPS=", self._fps)
            self._fps = 0
            self._t0 = time.time()


    def onKeyboard(self, window, key, scancode, action, mode):
        if key == GLApp.KEY_G and action == GLApp.PRESS:
            # Draw the GUI
            if self._renderer is None:
                self._renderer = GlfwRenderer(self.window(), False)
                self._renderer.process_inputs()
            else:
                self._renderer.shutdown()
                self._renderer = None
        elif key == GLApp.KEY_F and action == GLApp.PRESS:
            # Draw the field
            self._fa.drawField = not self._fa.drawField

        super(GLApp, self).onKeyboard(window, key, scancode, action, mode)


#------------------------------------------------------------------------------
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
            description="\nField Animation example",
            add_help=True,
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            prog=os.path.basename(sys.argv[0]))

    parser.add_argument('-f', '--draw_field', action='store_true',
            default=False,
            help=("Draw vector field as background image ")
            )
    parser.add_argument('-c', '--choose', choices="epole wind".split(),
            default="wind",
            help=("Choose field to animate ")
            )

    parser.add_argument('-p', '--fps', action='store_true', default=False,
            help=("Count Frames Per Second ")
            )

    parser.add_argument('-g', '--gui', action='store_true', default=False,
            help=("Add gui control window ")
            )

    options = parser.parse_args(sys.argv[1:])

    if options.choose == 'wind':
        field = np.load("wind_2016-11-20T00-00Z.npy")
    elif options.choose == 'epole':
        field = createField()

    app = GLApp('Field Animation', 360 * 3, 180 * 3, field, options)
    app.run()
